Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Exernet.Models
{
    public class Comment {
        [Key]
        public int Id { get; set; }
        public ExernetTask Task { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }
    }
}

Models/Formula.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Exernet.Models
{
    public class Formula
    {
        public int Id { get; set; }
        public ExernetTask Task { get; set; }
        public string FormulaURL { get; set; }
    }
}

Controllers/TaskController.cs
using Exernet.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Exernet.Filters;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using System.Text.RegularExpressions;
using Exernet.Code;
using Exernet.Search;

namespace Exernet.Controllers
{
    [Culture]
    public class TaskController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        [HttpGet]
        public ActionResult CreateTask(String input)
        {
            var md = new MarkdownDeep.Markdown();
            // Set options
            md.ExtraMode = true;
            md.SafeMode = false;
            string output = md.Transform(input);
            return View();
        }

        [HttpPost]
        public ActionResult CreateTask(ExernetTaskViewModel model, IEnumerable<HttpPostedFileBase> Images, string returnUrl)
        {
            ExernetTask task = new ExernetTask(); ;
            if (model.Id != 0)
            {
                task = db.Tasks.Where(a => a.Id.Equals(model.Id)).First();
                task.Tags.Clear();
                task.Answers.Clear();
                task.Videos.Clear();
            }
            task.Text = model.Text;
            task.Tags = GenerateTagsForTaskModel(model.Tags);
            task.Answers = GenerateAnswersForTaskModel(model.Answers);
            task.Videos = GenerateVideosForTaskModel(model.Videos);
            task.Title = model.Title;
            task.Category = model.Category;
            task.Block = true;
            task.UserId = User.Identity.GetUserId();
            task.UploadDate = DateTime.Now;
            if (model.Id == 0)
            {
                task.Images = UploadPicturesOnCloudinary(Images);
                db.Tasks.Add(task);
                db.Entry(task).State = EntityState.Added;
            }
            else
            {
                db.Entry(task).State = EntityState.Modified;
            }
            db.SaveChanges();

            return RedirectToAction("PostTask", new { id = GetId(model) });
        }

        private string[] parseForVideo(string[] listOfVideos)
        {
            string pattern = @".+?/?v=";
            string replacement1 = "//www.youtube.com/embed/";
            for (int i = 0; i < listOfVideos.Length; i++)
            {
                listOfVideos[i] = Regex.Replace(listOfVideos[i], pattern, replacement1);
            }

            return listOfVideos;
        }
        private ICollection<Video> GenerateVideosForTaskModel(string p)
        {
            if ((p != null) && p.Length > 0)
            {
                string[] listOfVideos = SplitString(p);
                listOfVideos = parseForVideo(listOfVideos);
                List<Video> Videos = new List<Video>();
                foreach (var str in listOfVideos)
                {
                    var Video = new Video();
                    Video.VideoURL = str;
                    Videos.Add(Video);
                }
                return Videos;
            }
            else
            {
                return null;
            }
        }

        private int GetId(ExernetTaskViewModel model)
        {
            int id;
            if (model.Id != 0)
            {
                id = model.Id;
            }
            else
            {
                id = db.Tasks.Local[0].Id;
            }
            return id;
        }

        private ICollection<Tag> GenerateTagsForTaskModel(string tags)
        {
            string[] listOfTags = SplitString(tags);

            var listOfTagsWithoutDuplicate = listOfTags.Distinct();

            List<Tag> Tags = new List<Tag>();

            foreach (string str in listOfTagsWithoutDuplicate)
            {
                var tag = db.Tags.FirstOrDefault(obj => obj.Text == str);
                if (tag == null)
                {
                    tag = new Tag();
                    tag.Text = str;
                }
                Tags.Add(tag);
            }
            return Tags;
        }

        private string[] SplitString(string term)
        {
            string[] str = term.Split(new string[] { ", ", ",", "; ", ";" }, StringSplitOptions.RemoveEmptyEntries);

            for (int i = 0; i < str.Length; i++)
            {
                str[i] = str[i].ToString().Trim();
            }
            return str;
        }


        private ICollection<Answer> GenerateAnswersForTaskModel(string term)
        {
            string[] listOfTags = SplitString(term);

            List<Answer> answers = new List<Answer>();

            foreach (string str in listOfTags)
            {
                Answer answer = new Answer();
                answer.Text = str;
                answers.Add(answer);
            }
            return answers;
        }

        public ActionResult PostTask(int id)
        {
            
            
            var task = new ExernetTask();
            task = db.Tasks.Find(id);
            return View(task);
        }

        public ActionResult EditTask(int id)
        {
            var model = db.Tasks.Find(id);
            ExernetTaskViewModel task = new ExernetTaskViewModel();

            task.Text = model.Text;
            task.Tags = GenerateStringTagsForTaskModel(model.Tags);
            task.Answers = GenerateStringAnswersForTaskModel(model.Answers);
            task.Videos = GenerateStringVideosForTaskModel(model.Videos);
            task.Title = model.Title;
            task.Category = model.Category;
            task.Id = id;
            return View(task);
        }

        private static string GenerateStringVideosForTaskModel(ICollection<Video> collection)
        {
            string stringOfVideos = string.Join("; ", collection.Select(obj => obj.VideoURL));
            return stringOfVideos;
        }

        private static string GenerateStringAnswersForTaskModel(ICollection<Answer> collection)
        {
            string stringOfAnswers = string.Join("; ", collection.Select(obj => obj.Text));
            return stringOfAnswers;
        }

        public static string GenerateStringTagsForTaskModel(ICollection<Tag> collection)
        {
            string stringOfTags = string.Join(", ", collection.Select(obj => obj.Text));

            return stringOfTags;
        }

        public static string GenerateStringCommentsForTaskModel(ICollection<Comment> collection)
        {
            string stringOfTags = string.Join(", ", collection.Select(obj => obj.Text));

            return stringOfTags;
        }

        public JsonResult TagSearch(string term)
        {

            var tags = db.Tags.Select(obj => obj.Text);

            return Json(tags, JsonRequestBehavior.AllowGet);
        }

        private List<Tag> GetTag(string searchString)
        {
            var tags = db.Tags.Where(a => a.Text.Contains(searchString)).ToList();
            return tags;

        }

        public ActionResult SetLike(int id, bool likeState)
        {
            var like = db.Tasks.Find(id).Likes.FirstOrDefault(obj => obj.User.UserName.Equals(User.Identity.Name));
            if (like == null)
            {
                like = new Like();
                like.Type = likeState;
                like.UserId = User.Identity.GetUserId();
                db.Tasks.Find(id).Likes.Add(like);
                db.Entry(db.Tasks.Find(id).Likes.FirstOrDefault(obj => obj.UserId.Equals(User.Identity.GetUserId()))).State = EntityState.Added;

            }
            else
            {
                if (like.Type == !likeState)
                {
                    like.Type = !like.Type;
                    foreach (var item in db.Tasks.Find(id).Likes)
                    {
                        db.Entry(item).State = EntityState.Modified;
                    }
                }
                else
                {
                    db.Tasks.Find(id).Likes.Remove(like);
                    foreach (var item in db.Tasks.Find(id).Likes)
                    {
                        db.Entry(item).State = EntityState.Deleted;
                    }
                }

            }
            db.SaveChanges();
            return PartialView(db.Tasks.Find(id));
        }

        public ActionResult GetTag()
        {
            var listOfTags = db.Tags.OrderByDescending(obj => obj.Tasks.Count).Take(25);
            return PartialView(listOfTags);
        }

        private List<Image> UploadPicturesOnCloudinary(IEnumerable<HttpPostedFileBase> pictures)
        {
            if (pictures == null) return null;
            List<Image> PictureUrls = new List<Image>();
            Cloudinary cloudinary = new Cloudinary(new Account(
           "goodcloud",
           "836668373272998",
           "HJ2Q7oe53Ru7muxKcpVj4ZdqVPQ"));
            foreach (var pic in pictures)
            {
                var uploadParams = new ImageUploadParams()
                {
                    File = new FileDescription(pic.FileName, pic.InputStream),
                    Folder = "Exernet/TaskPictures"
                };

                var uploadResult = cloudinary.Upload(uploadParams);
                var uplPath = uploadResult.Uri.AbsoluteUri;
                PictureUrls.Add(new Image() { ImageURL = uplPath });
            }
            return PictureUrls;
        }
        public ActionResult SolveTask(int id, string solveTry)
        {
            var solution = db.Tasks.Find(id).Solutions.FirstOrDefault(obj => obj.User.UserName.Equals(User.Identity.Name));

            var answer = db.Tasks.Find(id).Answers.FirstOrDefault(obj => obj.Text.Equals(solveTry));
            if (solution == null)
            {
                solution = new Solution();
                solution.UploadDate = DateTime.Now;
                solution.Correct = false;

Controllers/UserController.cs
using Exernet.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using System.IO;
using Exernet.Filters;

namespace Exernet.Controllers
{
    [Authorize]
    [Culture]
    public class UserController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public UserController()
            : this(new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext())))
        {
        }

        public UserController(UserManager<ApplicationUser> userManager)
        {
            UserManager = userManager;
        }

        public UserManager<ApplicationUser> UserManager { get; private set; }

        //
        // GET: /User/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /User/Details/id
        public ActionResult Details(string id)
        {
            if (id == null) return RedirectToAction("Index", "Home");
            var user = UserManager.FindByName(id);
            if (user == null) return RedirectToAction("Index", "Home");
            var taskList = GetFewTasksForPartialView(id, 1, 5);
            var userInfo = new ShowUserViewModel()
            {
                CommentsQuantity = user.Comments.Count,
                Email = user.Email,
                Rating = user.Rating,
                ResolvedTasksQuantity = user.Solutions.Count(x => x.Correct),
                Solutions = user.Solutions,
                SolutionsQuantity = user.Solutions.Count,
                Tasks = taskList,
                TasksQuantity = user.Tasks.Count,
                ProfileFotoURL=user.ProfileFotoURL,
                UserName=user.UserName
            };
            return View(userInfo);
        }

        // POST: /User/Details/id
        [HttpPost]
        public ActionResult Details(string id, HttpPostedFileBase fileUpload)
        {
            if (fileUpload == null)
            {
                return RedirectToAction("Details", new { id = id });
            }

            Cloudinary cloudinary = new Cloudinary(new Account(
            "goodcloud",
            "836668373272998",
            "HJ2Q7oe53Ru7muxKcpVj4ZdqVPQ"));

            var imageToDelete = UserManager.FindByName(id).ProfileFotoURL;
            var public_id = Path.GetFileNameWithoutExtension(imageToDelete);
            DelResParams deleteParams = new DelResParams()
            {
                PublicIds = new System.Collections.Generic.List<String>() { String.Format(@"Exernet/ProfilePictures/{0}",public_id) },
                Invalidate = true
            };
            cloudinary.DeleteResources(deleteParams);
            db.SaveChanges();
            var uploadParams = new ImageUploadParams()
            {
                File = new FileDescription(fileUpload.FileName, fileUpload.InputStream),
                Folder="Exernet/ProfilePictures"
            };

            var uploadResult = cloudinary.Upload(uploadParams);

            var uplPath = uploadResult.Uri.AbsoluteUri;

            db.Users.Find(User.Identity.GetUserId()).ProfileFotoURL = uplPath;
            //db.Entry().State = System.Data.Entity.EntityState.Added;
            db.SaveChanges();

            return RedirectToAction("Details", new {id = id });
        }

        //
        // GET: /User/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /User/Delete/5
        [HttpPost]
        public JsonResult Delete(string id)
        {
            try
            {
                var user = UserManager.FindByName(id);
                UserManager.Delete(user);
                return new JsonResult() { Data = id };
            }
            catch
            {
                return null;
            }
        }

        public ActionResult ViewListOfTasks(IEnumerable<ExernetTask> Model) {
            var list = Model.ToList();
            return PartialView("~/Views/Task/_ShowTaskOnly.cshtml",list);
        }

        public List<ExernetTask> GetFewTasksForPartialView(string UserName, int BlockNumber, int BlockSize)
        {
            var user = UserManager.FindByName(UserName);
            int startIndex = (BlockNumber - 1) * BlockSize;
            return (from p in user.Tasks.OrderByDescending(obj => obj.UploadDate) select p).Skip(startIndex).Take(BlockSize).ToList();
        }

        [HttpPost]
        public ActionResult InfiniteScroll(string UserName, int BlockNumber)
        {
            int BlockSize = 5;
            var tasks = GetFewTasksForPartialView(UserName, BlockNumber, BlockSize);
            JsonModel jsonModel = new JsonModel();
            jsonModel.NoMoreData = tasks.Count < BlockSize;
            jsonModel.HTMLString = RenderPartialViewToString("~/Views/Task/_ShowTaskOnly.cshtml", tasks);
            return Json(jsonModel);
        }

        private string RenderPartialViewToString(string viewName, List<ExernetTask> model)
        {
            ViewData.Model = model;

            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult =
                ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext
                (ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }

        public ActionResult ShowUsers() 
        {
            if (!User.IsInRole("Administrator")) return null;
            var users = UserManager.Users.ToArray() ;
            foreach (var user in users) 
            {
                user.IsAdmin = UserManager.IsInRole(user.Id,"Administrator");
            }
            return PartialView("~/Views/User/_AllUsersShort.cshtml",
                users);
        }
    }
}

Views/Task/Comment.cshtml
@model Exernet.Models.Comment



<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object pic img-circle" style="width: 50px" src="@Model.User.ProfileFotoURL" alt="">

    </a>
    <div class="media-body">
        <h4 class="media-heading">
            @Html.ActionLink(Model.User.UserName, "Details", "User", routeValues: new { id = Model.User.UserName }, htmlAttributes: new { title = String.Format("{0} account page", Model.User.UserName) })
            <small>@Model.Date</small>
        </h4>


        <div class="row well">
            <div class="col-md-12" style="word-break:break-all">
                <p>@Html.Raw(Model.Text)</p>
            </div>

        </div>


    </div>

</div>

Views/Task/CreateTask.cshtml
@using Exernet;
@model Exernet.Models.ExernetTaskViewModel
@{
    ViewBag.Title = "Create New Task";
}
@Scripts.Render("~/bundles/markdownjs")
@Styles.Render("~/Content/markdown")


    <title>Create task</title>
    <script src="~/Scripts/myJava.js"></script>
    <script src="~/Scripts/add-more-pictures.js"></script>
    <script src="~/Content/bootstrap-markdown/bootstrap-markdown.ru.js"></script>

  

<h2>@Resources.Resource.CreateTask</h2>
<div class="row">
    <div class="col-lg-6">

        @using (Html.BeginForm("CreateTask", "Task", new { ReturnUrl = "/Home/Index" }, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary()
            <div class="bs-component">
                <div class="form-group">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = Resources.Resource.TitlePlaceholder })
                </div>

                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Tags, new { @class = "form-control", id = "tags", placeholder = Resources.Resource.TagsPlaceholder })
                        </div>
                    </div>
                    <div class="col-md-3" align="right">
                        <div class="form-group">
                            @Html.DropDownListFor(m => m.Category, new SelectList(
                                                new List<Object>{
                                                new{ value = Resources.Category.Math, text = Resources.Category.Math},
                                                new{ value = Resources.Category.Cult, text = Resources.Category.Cult},
                                                new{ value = Resources.Category.Geography, text = Resources.Category.Geography},
                                                new{ value = Resources.Category.Physics, text = Resources.Category.Physics},
                                                new{ value = Resources.Category.Chemistry, text = Resources.Category.Chemistry},
                                                new{ value = Resources.Category.WithoutCategory, text = Resources.Category.WithoutCategory}

                            }, "value", "text", Resources.Category.WithoutCategory), new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                
                <div class="form-group">
                    @Html.TextAreaFor(m => m.Text, new { data_provide = "markdown", rows = "10" })
                </div>

                <div class="form-group">
                    @Html.TextBoxFor(m => m.Answers, new { @class = "form-control", placeholder = Resources.Resource.AnswersPlaceholder })
                </div>

                @*<div class="form-group">
                        <input type="file" name="Images[0]" id="Images" />
                    </div>*@

                <div class="form-group">
                    <label for="inputs" class="control-label">@Resources.Resource.AddImages</label>
                </div>
                    <table id="inputs"></table>
                <div class="form-group">
                    <input type="button" class="btn btn-xs btn-default" value=@Resources.Resource.AddMoreImage onclick="addInput()">
                </div>

                <div class="form-group">
                    @Html.TextBoxFor(m => m.Videos, new { @class = "form-control", placeholder = Resources.Resource.VideosPlaceholder })
                </div>

                <div class="form-group">
                    <input type="submit" value=@Resources.Resource.Submit class="btn btn-success" />
                </div>
            </div>




        }

    </div>
    <div class="col-lg-6">
        @{ Html.RenderPartial("Formula"); }
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Task/PostTask.cshtml
@using Exernet;
@model Exernet.Models.ExernetTask
<!DOCTYPE html>
<html lang="en">
@{
    ViewBag.Title = "PostTask";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>@Model.Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>@Model.Title</h1>

                <div class="row">
                    <div class="col-md-8">
                        <p class="lead">
                            @Resources.Resource.By @Html.ActionLink(Model.User.UserName, "Details", "User", routeValues: new { id = Model.User.UserName }, htmlAttributes: new { title = String.Format("{0} account page", Model.User.UserName) })
                        </p>
                    </div>
                    <div class="col-md-4" align="right">
                        @foreach (var str in Model.Tags.Select(obj => obj.Text))
                        {
                            <a href="http://localhost:54084/Task/ShowTags?tag=@str" class="label label-primary">@str</a>
                        }
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div><p><span class="glyphicon glyphicon-time"></span> @Resources.Resource.PostedOn @Model.UploadDate </p></div>
                    </div>
                    <div class="col-md-4" align="right">
                        <div><p><span class="glyphicon glyphicon-fire"></span> @Resources.Category.CategoryOfTask: @Model.Category  </p></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        @Html.ActionLink(Resources.Resource.Edit, "EditTask", "Task", routeValues: new { id = Model.Id }, htmlAttributes: new { title = "Manage", @class = "btn btn-default btn-xs" })
                    </div>
                    <div class="col-md-6" align=right>


                        @Ajax.ActionLink(" ", "SetLike", new { id = Model.Id, likeState = true }, new AjaxOptions { UpdateTargetId = "SetLike" }, new { @class = "glyphicon glyphicon-thumbs-up" })
                        <div id="SetLike">
                            @{ Html.RenderPartial("/Views/Task/SetLike.cshtml", Model); }
                        </div>
                        @Ajax.ActionLink(" ", "SetLike", new { id = Model.Id, likeState = false }, new AjaxOptions { UpdateTargetId = "SetLike" }, new { @class = "glyphicon glyphicon-thumbs-down" })
                    </div>
                </div>
                <hr />

                <div class="row">
                    <div class="col-md-12 img img-responsive" style="word-break: break-all; width:inherit">
                        <p class="img-responsive">@Html.Raw(System.Web.HttpUtility.HtmlDecode(@MarkdownHelper.Markdown(Model.Text)))</p>
                    </div>
                </div>
                <hr />

                @if (Model.Videos.Count > 0)
                {
                    <div class="embed-responsive embed-responsive-16by9">
                        @foreach (var str in Model.Videos.Select(obj => obj.VideoURL))
                        {
                            <iframe class="embed-responsive-item" src=@str frameborder="0" allowfullscreen></iframe>

                        }
                    </div>
                    <hr />
                }
                <div class="row form-group">
                    @Html.Partial("_ShowImagesWithZoom", Model.Images)
                </div>
                <hr>
                <div class=" form-group">
                    @Html.Action("CheckSolve", "Task", new { id = Model.Id })
                </div>
                @using (Ajax.BeginForm("LeaveComment", new { id = Model.Id }, new AjaxOptions
                    {
                        UpdateTargetId = "comment",
                        InsertionMode = InsertionMode.InsertBefore
                    }))
                {
                    <div class="well">
                        <h4>@Resources.Resource.LeaveComment:</h4>
                        <form role="form">
                            <div class="form-group">
                                <textarea class="form-control" name="commentText" rows="3"></textarea>
                            </div>
                            <button type="submit" value="Comment" class="btn btn-primary">@Resources.Resource.Submit</button>
                        </form>
                    </div>
                }
                <hr>

                <div class="media" id="comment">
                    <a class="pull-left" href="#">
                    </a>
                </div>

                @foreach (var comment in Model.Comments.OrderByDescending(obj => obj.Date))
                {
                    Html.RenderPartial("/Views/Task/Comment.cshtml", comment);
                }

            </div>
            <div class="col-md-4">
                <div id="GetTag">
                    @Html.Action("GetTag", "Task")
                </div>
            </div>
        </div>
    </div>



</body>
</html>

Views/Task/SolveTask.cshtml
@model Exernet.Models.Solution

@if (!Model.Correct)
{
    <div class="alert alert-info">
        @Html.Action("CheckSolve", "Task", new { id = Model.Task.Id })
        @Resources.Resource.WrongSolve
    </div>
}
else
{
    <div class="alert alert-success">
  @Resources.Resource.YouSolve
</div>
}

Views/Task/_ShowTaskOnly.cshtml
@using Microsoft.AspNet.Identity
@model List<Exernet.Models.ExernetTask>
@foreach(var item in Model){
    <div class="item col-md-12" id="element_@item.Id">
    <div class="panel panel-default">
        <div class="panel-heading" style="word-break:break-all;">
            <div class="row">
                <div class="col-md-8 pull-left">
                    @Html.ActionLink('"' + item.Title + '"', "PostTask", "Task", routeValues: new { id = item.Id }, htmlAttributes: new { title = String.Format("Task \"{0}\" view page", item.Title) })
                    @Resources.Resource.By
                    @Html.ActionLink(item.User.UserName, "Details", "User", routeValues: new { id = item.User.UserName }, htmlAttributes: new { title = String.Format(@Resources.Resource.AccountPg+" \"{0}\"", item.User.UserName) })
                    . @Resources.Resource.PostedOn @item.UploadDate
                </div>

                <div class="col-md-4" >
                    <div class="row">
                        <div class="col-md-11" align="right">
                            @Resources.Resource.Tags
                            @foreach (var str in item.Tags.Select(obj => obj.Text))
                            {
                               <a href="http://localhost:54084/Task/ShowTags?tag=@str" class="label label-primary">@str</a>
                            }
                        </div>
                        @if(User.IsInRole("Administrator"))
                        { 
                        <div class="col-md-1">
                            <button type="button" class="close delete" id="@item.Id" name="delete"  data-toggle="tooltip" data-placement="top" title="Delete"><span aria-hidden="true">&times;</span><span class="sr-only">Delete</span></button>
                        </div>
                        }
                    </div>
                </div>

                
            </div>

        </div>
        <div class="panel-body img-responsive" style="word-break:break-all">
            <div class="col-md-12 ">
                @Html.Raw(System.Web.HttpUtility.HtmlDecode(@MarkdownHelper.Markdown(item.Text)))
            </div>
            @if (@item.Images.Count != 0)
            {
                <button type="button" class="btn btn-default btn-xs" data-toggle="collapse" data-target="#images_@item.Id@item.User.UserName">
                    <div class="glyphicon glyphicon-paperclip"></div> @Resources.Resource.ShowAttachedImages
                </button>
                
                <div id="images_@item.Id@item.User.UserName" class="panel-collapse collapse">
                    <div class="panel-body">
                        @Html.Partial("_ShowImagesWithZoom", @item.Images)
                    </div>
                </div>
                @Html.ActionLink(@Resources.Resource.GoToThisTask, "PostTask", "Task", routeValues: new { id = item.Id }, htmlAttributes: new {@class="btn btn-info btn-xs pull-right", title = String.Format("Task \"{0}\" view page", item.Title) })
            }
        </div>
    </div>
</div>
}
<script type="text/javascript">
    $(".delete").click(function () {
        var id = $(this).attr("id");
        $.ajax({
            url: "http://localhost:54084/Task/DeleteTask",
            dataType: "json",
            type: "POST",
            data: { id: id },
            success: function (data) {
                $("#element_" + data).remove();
            },
            error: function (e) {
                alert("cannot delete this task");
            }
        });
    });
</script>